# Generated by Django 5.1.5 on 2025-02-05 16:36

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0003_alter_figuresalbum_cover_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=common.storage.uploading_path_getter, verbose_name='файл'),
        ),
    ]
