# Generated by Django 5.1.5 on 2025-01-27 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='когда обновлен')),
                ('title', models.CharField(max_length=127, verbose_name='название')),
                ('detailed', models.TextField(blank=True, verbose_name='описание')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss_created', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss_updated', to=settings.AUTH_USER_MODEL, verbose_name='кем обновлён')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='когда обновлен')),
                ('val', models.PositiveSmallIntegerField(verbose_name='Балл')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss_created', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_ratings', to='documents.document', verbose_name='документ')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss_updated', to=settings.AUTH_USER_MODEL, verbose_name='кем обновлён')),
            ],
            options={
                'verbose_name': 'оценка документа',
                'verbose_name_plural': 'оценки документа',
            },
        ),
        migrations.CreateModel(
            name='DocumentsAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='когда обновлен')),
                ('title', models.CharField(max_length=127, verbose_name='название')),
                ('detailed', models.TextField(blank=True, verbose_name='описание')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss_created', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss_updated', to=settings.AUTH_USER_MODEL, verbose_name='кем обновлён')),
            ],
            options={
                'verbose_name': 'альбом документов',
                'verbose_name_plural': 'альбомы документов',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='documents_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentsalbum', verbose_name='альбом'),
        ),
    ]
