# Generated by Django 5.1.5 on 2025-01-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentrating_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentrating',
            old_name='val',
            new_name='value',
        ),
    ]
