# Generated by Django 5.1.5 on 2025-02-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
