# Generated by Django 5.1.4 on 2025-01-07 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='когда обновлен')),
                ('title', models.CharField(max_length=127, verbose_name='заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='подзаголовок')),
                ('text', models.TextField(blank=True, verbose_name='текст записи')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss_created', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss_updated', to=settings.AUTH_USER_MODEL, verbose_name='кем обновлён')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
