# Generated by Django 5.1.5 on 2025-01-27 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpostcomment_blogrubric_blogpost_blog_rubric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogpostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда создан')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost_likes', to='blog.blogpost', verbose_name='пост')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss_created', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
            ],
            options={
                'verbose_name': 'лайк к посту',
                'verbose_name_plural': 'лайки к посту',
            },
        ),
    ]
