# Generated by Django 5.1.5 on 2025-01-28 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogposttag_blogpost_blogpost_tags'),
        ('figures', '0003_alter_figuresalbum_cover_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrubric',
            name='cover_figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_rubrics_covered', to='figures.figure', verbose_name='обложка'),
        ),
    ]
