# Generated by Django 5.1.5 on 2025-01-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogrubric_cover_figure'),
        ('documents', '0004_documentsalbum_cover_figure'),
        ('figures', '0003_alter_figuresalbum_cover_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='documents',
            field=models.ManyToManyField(related_name='blogposts_reffering', to='documents.document', verbose_name='документы'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='figures',
            field=models.ManyToManyField(related_name='blogposts_referring', to='figures.figure', verbose_name='иллюстрации'),
        ),
    ]
