# Generated by Django 5.1.5 on 2025-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_documents_blogpost_figures'),
        ('documents', '0004_documentsalbum_cover_figure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='documents',
            field=models.ManyToManyField(related_name='blogposts_referring', to='documents.document', verbose_name='документы'),
        ),
    ]
