# Generated by Django 5.1.5 on 2025-02-13 18:04

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogrubric',
            managers=[
                ('api_v1', django.db.models.manager.Manager()),
            ],
        ),
    ]
