# Generated by Django 5.1.5 on 2025-02-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogrubric_managers'),
        ('documents', '0008_alter_document_file'),
        ('figures', '0005_alter_figure_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, related_name='blogposts_referring', to='documents.document', verbose_name='документы'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='figures',
            field=models.ManyToManyField(blank=True, null=True, related_name='blogposts_referring', to='figures.figure', verbose_name='иллюстрации'),
        ),
    ]
