# Generated by Django 5.1.5 on 2025-02-14 13:41

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpost_documents_alter_blogpost_figures'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogposttag',
            managers=[
                ('api_v1', django.db.models.manager.Manager()),
            ],
        ),
    ]
