# Generated by Django 5.1.5 on 2025-02-17 03:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpost_managers_alter_blogposttag_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
                ('api_v1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blogposttag',
            managers=[
                ('api_v1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blogrubric',
            managers=[
                ('api_v1', django.db.models.manager.Manager()),
            ],
        ),
    ]
