# Generated by Django 5.1.5 on 2025-02-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpost_managers_alter_blogposttag_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='blogposttag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='blogrubric',
            managers=[
            ],
        ),
    ]
