# Generated by Django 5.1.5 on 2025-02-17 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogpost_managers_alter_blogposttag_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposttag',
            name='title',
            field=models.CharField(max_length=127, unique=True, verbose_name='название'),
        ),
        migrations.AlterUniqueTogether(
            name='blogpostlike',
            unique_together={('blogpost', 'created_by')},
        ),
    ]
