volumes:
  pgdata:

networks:
  vznw:

services:

  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: vzntp
      POSTGRES_PASSWORD: Qwerty123456
      POSTGRES_DB: vzntp25
    volumes:
        - pgdata:/var/lib/postgresql/data
    networks:
      vznw:

  web:
    build:
      context: .
    container_name: web_app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - pgdb
    links:
      - pgdb:pgdb
    networks:
      vznw: